blog/urls.py
from django.urls import path
from blog.views import *
app_name = 'blog'

urlpatterns = [
    path('',home_view,name='index'),
    path('<int:pid>',single_view,name='single'),
    path('category/<str:cat_name>',home_view,name='category'),
    path('tag/<str:tag_name>',home_view,name='tag'),
    path('author/<str:author_username>',home_view,name='author'),
    path('search/',blog_search,name='search'),
    # path('rss/feed/', LatestEntriesFeed()),
    # path('test',test,name='test'),
]

kshfplast/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
import debug_toolbar
sitemaps = {
    'static' : StaticViewSitemap,
    'blog' : BlogSitemap,
}



urlpatterns = [
     path('admin/', admin.site.urls),
     path('', include('website.urls')),
     path('blog', include('blog.urls')),
     path('accounts/',include('accounts.urls')),
     path(r'', include('django.contrib.auth.urls')),
     path('tinymce/', include('tinymce.urls')),
    #  path('summernote/', include('django_summernote.urls')),
     path('sitemap.xml' , sitemap , {'sitemaps' : sitemaps},
        name = 'django.contrib.sitemaps.views.sitemap'),
     path('captcha/', include('captcha.urls')),
     path('robots.txt', include('robots.urls')),
     path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from .views import *
app_name = 'website'
urlpatterns = [
    path('',index_view,name='index'),
    path('about',about_view,name='about'),
    path('contact',contact_view,name='contact'),
    path('newsletter',newsletter_view,name='newsletter'),

]

website/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255, blank=True, null=True)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['created_date']

    def __str__(self):
        return self.name
    
class Newsletter(models.Model):
    email = models.EmailField()
    def __str__(self):
        return self.email 

website/forms.py
from django import forms
from website.models import Contact,Newsletter
from captcha.fields import CaptchaField

class ContactForm(forms.ModelForm):
    captcha = CaptchaField()
    class Meta:
        model = Contact
        fields = '__all__'


class Newsletterform(forms.ModelForm):
    class Meta:
        model = Newsletter
        fields = '__all__'

website/views.py
from django.shortcuts import render
from django.http import HttpResponse,JsonResponse,HttpResponseRedirect
from website.forms import ContactForm,Newsletterform
from django.contrib import messages
# Create your views here.

def index_view (request):
    return render(request,'website/index.html') 

def about_view (request):
    return render(request,'website/about.html') 

def contact_view (request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.name = "Unknown"  
            form.save()
            messages.add_message(request,messages.SUCCESS,'your ticket submitted succesfully.')
        else:
            messages.add_message(request,messages.ERROR,"your ticket didn't submit")
    form = ContactForm() 
    return render(request,'website/contact.html',{'form':form}) 

def newsletter_view(request):
    if request.method == 'POST':
        form = Newsletterform(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request,messages.SUCCESS,'your ticket submitted succesfully.')
            return HttpResponseRedirect('/')
        else:
             messages.add_message(request,messages.ERROR,"your ticket didn't submit")
             return HttpResponseRedirect('/')
    form = Newsletterform()
    return render(request,'website/index.html',{'form':form}) 

templates/website/about.html
{% extends 'base.html' %}
{% load static %}
{% block contents %}
    <!-- breadcrumb start-->
    <section class="breadcrumb breadcrumb_bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb_iner">
                        <div class="breadcrumb_iner_item">
                            <h2>about us</h2>
                            <p> <a href="{% url 'website:index' %}">Home</a> <span>-</span>about us</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumb start-->

    <!-- service part start-->
    <section class="service_part section_padding">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-3 col-sm-6 col-md-6">
                    <div class="single_service_part">
                        <i class="flaticon-chip"></i>
                        <span class="line"></span>
                        <h3>Advance Technology</h3>
                        <p>All fish day af emale very appear moved seas above Fifth them grass gathere above
                            male moveth whose life rule she gathering seas of is sea night</p>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6 col-md-6">
                    <div class="single_service_part">
                        <i class="flaticon-cap"></i>
                        <span class="line"></span>
                        <h3>world Quality SErvice</h3>
                        <p>All fish day af emale very appear moved seas above Fifth them grass gathere above
                            male moveth whose life rule she gathering seas of is sea night</p>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6 col-md-6">
                    <div class="single_service_part">
                        <i class="flaticon-wallet"></i>
                        <span class="line"></span>
                        <h3>world Quality SErvice</h3>
                        <p>All fish day af emale very appear moved seas above Fifth them grass gathere above
                            male moveth whose life rule she gathering seas of is sea night</p>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6 col-md-6">
                    <div class="single_service_part">
                        <i class="flaticon-audio"></i>
                        <span class="line"></span>
                        <h3>Lifetime support</h3>
                        <p>All fish day af emale very appear moved seas above Fifth them grass gathere above
                            male moveth whose life rule she gathering seas of is sea night</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- service part start-->

    <!-- about part start-->
    <section class="about_part section_bg section_padding">
        <div class="container">
            <div class="row align-items-center justify-content-between">
                <div class="col-md-6 col-lg-6">
                    <div class="about_img">
                        <img src="{% static 'img/about_img_1.png' %}" alt="">
                    </div>
                </div>
                <div class="col-md-5 col-lg-5">
                    <div class="about_text">
                        <h2>We Are Committed <br>
                            To Customer Satisfaction</h2>
                        <h4>Their be void upon image lights you fifth seed wherein for very mud
                            the winged his days fruitful. Stars fruit fourth.</h4>
                        <p>Fifth darkness lights after sixth first Firmament morning and the Green saying greatn
                            forth behold open said First she'd saying have any question availbla now their void
                            upon image lights. You fifth seed for very the</p>
                        <a href="#" class="btn_2">read more</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- about part start-->

    <!--::industries start::-->
    <section class="our_Professional single_page_Professional section_padding">
        <div class="container">
            <div class="row">
                <div class="col-xl-4">
                    <div class="section_tittle">
                        <h2>Meet Experienced
                            Professional</h2>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-3 col-sm-6">
                    <div class="single_industries">
                        <img src="{% static 'img/Professional/our_professional_1.png' %}" alt="">
                        <div class="single_industries_text">
                            <h3>Andrew Flentop</h3>
                            <p>System Engineer</p>
                            <div class="social_icon">
                                <a href="#"><i class="flaticon-facebook"></i></a>
                                <a href="#"><i class="flaticon-twitter"></i></a>
                                <a href="#"><i class="flaticon-skype"></i></a>
                                <a href="#"><i class="flaticon-instagram"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="single_industries">
                        <img src="{% static 'img/Professional/our_professional_2.png' %}" alt="">
                        <div class="single_industries_text">
                            <h3>Andrew Flentop</h3>
                            <p>System Engineer</p>
                            <div class="social_icon">
                                <a href="#"><i class="flaticon-facebook"></i></a>
                                <a href="#"><i class="flaticon-twitter"></i></a>
                                <a href="#"><i class="flaticon-skype"></i></a>
                                <a href="#"><i class="flaticon-instagram"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="single_industries">
                        <img src="{% static 'img/Professional/our_professional_3.png' %}" alt="">
                        <div class="single_industries_text">
                            <h3>Andrew Flentop</h3>
                            <p>System Engineer</p>
                            <div class="social_icon">
                                <a href="#"><i class="flaticon-facebook"></i></a>
                                <a href="#"><i class="flaticon-twitter"></i></a>
                                <a href="#"><i class="flaticon-skype"></i></a>
                                <a href="#"><i class="flaticon-instagram"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="single_industries">
                        <img src="{% static 'img/Professional/our_professional_4.png' %}" alt="">
                        <div class="single_industries_text">
                            <h3>Andrew Flentop</h3>
                            <p>System Engineer</p>
                            <div class="social_icon">
                                <a href="#"><i class="flaticon-facebook"></i></a>
                                <a href="#"><i class="flaticon-twitter"></i></a>
                                <a href="#"><i class="flaticon-skype"></i></a>
                                <a href="#"><i class="flaticon-instagram"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--::industries end::-->

    <!--::subscribe area start::-->
    <!-- <section class="subscribe_area">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-12">
                    <div class="subscribe_iner">
                        <div class="row align-items-center">
                            <div class="col-lg-5 col-xl-5">
                                <div class="subscribe_area_tittle">
                                    <h2>Do You Have a Question?</h2>
                                </div>
                            </div>
                            <div class="col-lg-7 col-xl-6">
                                <div id="mc_embed_signup">
                                    <aside class="single_sidebar_widget newsletter_widget">
                                        <form target="_blank"
                                            action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
                                            method="get">
                                            <div class="form-group">
                                                <input type="email" class="form-control" onfocus="this.placeholder = ''"
                                                    onblur="this.placeholder = 'Enter email'" placeholder='Enter email'
                                                    required>
                                            </div>
                                            <button class="btn_2" type="submit">Subscribe</button>

                                            <div class="info"></div>
                                        </form>
                                    </aside>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section> -->
    <!--::subscribe area end::-->
{% endblock %}

templates/website/contact.html
{% extends 'base.html' %}
{% load static %}
{% block contents %}
    <!-- breadcrumb start-->
    <section class="breadcrumb breadcrumb_bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb_iner">
                        <div class="breadcrumb_iner_item">
                            <h2>contact us</h2>
                            <p> <a href="{% url 'website:index' %}">Home</a> <span>-</span>contact us</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumb start-->

    <!-- ================ contact section start ================= -->
    <section class="contact-section">
        <div class="container">
            <div class="d-none d-sm-block mb-5 pb-4">
                <div id="map" style="height: 480px;"></div>
                <script data-cfasync="false" ></script><script>
                    function initMap() {
                        var uluru = {
                            lat: -25.363,
                            lng: 131.044
                        };
                        var grayStyles = [{
                                featureType: "all",
                                stylers: [{
                                        saturation: -90
                                    },
                                    {
                                        lightness: 50
                                    }
                                ]
                            },
                            {
                                elementType: 'labels.text.fill',
                                stylers: [{
                                    color: '#ccdee9'
                                }]
                            }
                        ];
                        var map = new google.maps.Map(document.getElementById('map'), {
                            center: {
                                lat: -31.197,
                                lng: 150.744
                            },
                            zoom: 9,
                            styles: grayStyles,
                            scrollwheel: false
                        });
                    }
                </script>
                <script
                    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDpfS1oRGreGSBU5HHjMmQ3o5NLw7VdJ6I&callback=initMap">
                </script>

            </div>
            <div class="row">
                <div class="col-12">
                    <h2 class="contact-title">Get in Touch</h2>
                </div>
                <div class="col-lg-8">
                    <form class="form-contact contact_form" action="{% url 'website:contact' %}" method="post"
                        novalidate="novalidate">
                        <div class="row">
                            {% csrf_token %}
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <input class="form-control" name="name"  type="text"
                                        onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter your name'"
                                        placeholder='Enter your name'>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <input class="form-control" name="email"  type="email"
                                        pattern="[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{1,63}$"
                                        onfocus="this.placeholder = ''"
                                        onblur="this.placeholder = 'Enter email address'"
                                        placeholder='Enter email address'>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-group">
                                    <input class="form-control" name="subject"  type="text"
                                        onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Subject'"
                                        placeholder='Enter Subject'>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-group">

                                    <textarea class="form-control w-100" name="message"  cols="30" rows="9"
                                        onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Message'"
                                        placeholder='Enter Message'></textarea>
                                </div>
                            </div>   
                        </div>
                        {{form.captcha}}
                        <div class="form-group mt-3">
                            <button type="submit" class="button button-contactForm btn_2">Send Message</button>
                        </div>
                    </form>
                </div>
                <div class="col-lg-4">
                    <div class="media contact-info">
                        <span class="contact-info__icon"><i class="ti-home"></i></span>
                        <div class="media-body">
                            <h3>Buttonwood, California.</h3>
                            <p>Rosemead, CA 91770</p>
                        </div>
                    </div>
                    <div class="media contact-info">
                        <span class="contact-info__icon"><i class="ti-tablet"></i></span>
                        <div class="media-body">
                            <h3>00 (440) 9865 562</h3>
                            <p>Mon to Fri 9am to 6pm</p>
                        </div>
                    </div>
                    <div class="media contact-info">
                        <span class="contact-info__icon"><i class="ti-email"></i></span>
                        <div class="media-body">
                            <h3>Enter your email</h3>
                            <p>Send us your query anytime!</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ================ contact section end ================= -->

    <!--::subscribe area start::-->
    <!-- <section class="subscribe_area">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-12">
                    <div class="subscribe_iner">
                        <div class="row align-items-center">
                            <div class="col-lg-5 col-xl-5">
                                <div class="subscribe_area_tittle">
                                    <h2>Do You Have a Question?</h2>
                                </div>
                            </div>
                            <div class="col-lg-7 col-xl-6">
                                <div id="mc_embed_signup">
                                    <aside class="single_sidebar_widget newsletter_widget">
                                        <form target="_blank"
                                            action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
                                            method="get">
                                            <div class="form-group">
                                                <input type="email" class="form-control" onfocus="this.placeholder = ''"
                                                    onblur="this.placeholder = 'Enter email'" placeholder='Enter email'
                                                    required>
                                            </div>
                                            <button class="btn_2" type="submit">Subscribe</button>

                                            <div class="info"></div>
                                        </form>
                                    </aside>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section> -->
    <!--::subscribe area end::-->
{% endblock %}

templates/website/home-latest-posts.html
{% load static %}
{% load blog_tags %}
<section class="catagory_post">
    <div class="container">
        <div class="row">
            <div class="col-xl-4">
                <div class="section_tittle">
                    <h2>Latest From Our
                        Blog page</h2>
                </div>
            </div>
        </div>
        <div class="row">
            {% for post in posts %}
            <div class="col-sm-6 col-lg-4">
                
                <div class="single_catagory_post post_2">
                    <div class="category_post_img">
                        <img src="{{post.image.url}}" alt="">
                        <a href="{% url 'blog:single' pid=post.id %}" class="category_btn"></a>
                    </div>
                    <div class="post_text_1 pr_30">
                        <p><span>By {% if post.author.first_name and post.author.last_name %}
                                        {{ post.author.get_full_name }}  {# Shows "First Last" if both exist #}
                                    {% else %}
                                        {{ post.author.username }}  {# Falls back to username #}
                                    {% endif %}</span> / {{post.published_date|date:"d M, Y"}}</p>
                        <a href="{% url 'blog:single' pid=post.id %}">
                            <h3>{{post.title}}</h3>
                        </a>
                        <div class="post_icon">
                            <ul>
                                <li><i class="ti-comment"></i>{% comments_count post.id %} Comments</li>
                                <li>
                                    <i class="ti-bookmark"></i>  <!-- Icon appears once -->
                                    {% for cat in post.category.all %}
                                    <a href="{% url 'blog:category' cat_name=cat.name %}" style="color: black;"> {{ cat.name }}{% if not forloop.last %}, {% endif %}  <!-- Comma between categories -->
                                    {% empty %}
                                        No categories  <!-- Fallback if no categories exist -->
                                    {% endfor %}
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                
            </div>
            {% endfor %}

        </div>
    </div>
</section>