blog/urls.py
from django.urls import path
from blog.views import *
app_name = 'blog'

urlpatterns = [
    path('',home_view,name='index'),
    path('<int:pid>',single_view,name='single'),
    path('category/<str:cat_name>',home_view,name='category'),
    path('tag/<str:tag_name>',home_view,name='tag'),
    path('author/<str:author_username>',home_view,name='author'),
    path('search/',blog_search,name='search'),
    # path('rss/feed/', LatestEntriesFeed()),
    # path('test',test,name='test'),
]

kshfplast/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
import debug_toolbar
sitemaps = {
    'static' : StaticViewSitemap,
    'blog' : BlogSitemap,
}



urlpatterns = [
     path('admin/', admin.site.urls),
     path('', include('website.urls')),
     path('blog', include('blog.urls')),
     path('accounts/',include('accounts.urls')),
     path(r'', include('django.contrib.auth.urls')),
     path('tinymce/', include('tinymce.urls')),
    #  path('summernote/', include('django_summernote.urls')),
     path('sitemap.xml' , sitemap , {'sitemaps' : sitemaps},
        name = 'django.contrib.sitemaps.views.sitemap'),
     path('captcha/', include('captcha.urls')),
     path('robots.txt', include('robots.urls')),
     path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from .views import *
app_name = 'website'
urlpatterns = [
    path('',index_view,name='index'),
    path('about',about_view,name='about'),
    path('contact',contact_view,name='contact'),
    path('newsletter',newsletter_view,name='newsletter'),

]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
from tinymce.models import HTMLField
# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255)
    def __str__(self):
        return self.name

class Post(models.Model):
    category = models.ManyToManyField(Category)
    image = models.ImageField(upload_to='blog',default='blog/default.png')
    author = models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    title = models.CharField(max_length=255)
    content = models.TextField()
    tags = TaggableManager()
    counted_views = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    login_require = models.BooleanField(default=False)
    published_date = models.DateTimeField(null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_date']

    def __str__(self):
        return "{} - {}".format(self.title,self.id)
    
    def get_absolute_url(self):
        return reverse('blog:single',kwargs={'pid':self.id})
    
class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=100)
    message = models.TextField()
    approved = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['-created_date']
        
    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from blog.models import Comment
from captcha.fields import CaptchaField
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['post','name','email','subject','message']

blog/views.py
from django.shortcuts import render,get_object_or_404
from blog.models import Post,Comment
from django.utils import timezone
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from blog.forms import CommentForm
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse
# Create your views here.

def home_view (request,**kwargs):
    posts = Post.objects.filter(published_date__lte=timezone.now(),status=1)
    if kwargs.get('author_username') != None:
        posts = posts.filter(author__username=kwargs['author_username'])
    if kwargs.get('cat_name') != None:
        posts = posts.filter(category__name=kwargs['cat_name'])
    if kwargs.get('tag_name') != None:
        posts = posts.filter(tags__name__in=[kwargs['tag_name']])
    posts = Paginator(posts,4)
    try:
        page_number = request.GET.get('page')
        posts = posts.get_page(page_number)
    except PageNotAnInteger:
        posts = posts.get_page(1)
    except EmptyPage:
        posts = posts.get_page(1)
    context = {'posts':posts}
    return render(request,'blog/blog.html', context) 

def single_view (request,pid):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request,messages.SUCCESS,'your comment submitted succesfully.')
        else:
            messages.add_message(request,messages.ERROR,'your comment didn\'t submit.')
    form = CommentForm()
    posts = Post.objects.filter(published_date__lte=timezone.now(),status=1)
    post = get_object_or_404(posts,pk=pid)
    if not post.login_require:
        comments = Comment.objects.filter(post=post.id,approved=True)
        all_posts = Post.objects.filter(published_date__lte=timezone.now(),status=1).order_by('published_date')
        current_index = list(all_posts).index(post)
        previous_post = all_posts[current_index - 1] if current_index > 0 else None
        next_post = all_posts[current_index + 1] if current_index < len(all_posts) - 1 else None
        post.counted_views += 1
        post.save()
        context = {
            'post' :post,
            'previous_post' :previous_post,
            'next_post' :next_post,
            'comments' : comments,
            'form' : form
            }
        return render(request,'blog/single-blog.html',context) 
    else:
        return HttpResponseRedirect(reverse('accounts:login'))

def blog_category (request,cat_name):
    posts = Post.objects.filter(published_date__lte=timezone.now(),status=1)
    posts = posts.filter(category__name=cat_name)
    context = {'posts':posts}
    return render(request,'blog/blog.html',context) 

def blog_search(request):
    posts = Post.objects.filter(published_date__lte=timezone.now(),status=1)
    if request.method == 'GET':
        if s := request.GET.get('s'):
            posts = posts.filter(content__contains=s)
    context = {'posts':posts}
    return render(request,'blog/blog.html',context)

templates/blog/blog-categories.html
{% load static %}
<aside class="single_sidebar_widget post_category_widget">
    <h4 class="widget_title">Category</h4>
    <ul class="list cat-list">
        {% for name,count in categories.items %}
        <li>
            <a href="{% url 'blog:category' cat_name=name %}" class="d-flex">
                <p>{{name}} ({{count}})</p>            
            </a>
        </li>
        {% endfor %}
    </ul>
</aside>

templates/blog/blog-latest-posts.html
{% load humanize %}
{% load static %}
<aside class="single_sidebar_widget popular_post_widget">
    <h3 class="widget_title">Recent Post</h3>
    {% for post in posts %}
    <div class="media post_item">   
        <img src="{{post.image.url}}" width="50%" alt="post">
        <div class="media-body">
            <a href="{% url 'blog:single' pid=post.id %}">
                <h3>{{post.title}}</h3>
            </a>
            <p>{{post.published_date|naturaltime}}</p>
        </div>
    </div>
    {% endfor %}
</aside>

templates/blog/blog-newsletter.html
{% load static %}
<aside class="single_sidebar_widget newsletter_widget">
    <h4 class="widget_title">Newsletter</h4>

    <form action="{% url 'website:newsletter' %}" method="Post">
        {% csrf_token %}
        <div class="form-group">
            <input name='email' type="email" class="form-control" onfocus="this.placeholder = ''"
                onblur="this.placeholder = 'Enter email'" placeholder='Enter email' required>
        </div>
        <button class="button rounded-0 primary-bg text-white w-100 btn_1"
            type="submit">Subscribe</button>
    </form>
</aside>

templates/blog/blog-search.html
{% load static %}
<aside class="single_sidebar_widget search_widget">
    <form action="{% url 'blog:search' %}">
        <div class="form-group">
            <div class="input-group mb-3">
                <input type="text" name="s" class="form-control" placeholder='Search Keyword'
                    onfocus="this.placeholder = ''"
                    onblur="this.placeholder = 'Search Keyword'">
                <div class="input-group-append">
                    <button class="btn" type="button"><i class="ti-search"></i></button>
                </div>
            </div>
        </div>
        <button class="button rounded-0 primary-bg text-white w-100 btn_1"
            type="submit">Search</button>
    </form>
</aside>

templates/blog/blog-tags.html
{% load static %}

<aside class="single_sidebar_widget tag_cloud_widget">
    <h4 class="widget_title">Tag Clouds</h4>
    <ul class="list">
        {% for tag in post.tags.all %}
        <li>
            <a href="{% url 'blog:tag' tag_name=tag.name %}">{{tag.name}}</a>
        </li>
        {% endfor %}
    </ul>
</aside>

templates/blog/blog.html
{% extends 'base.html' %}
{% load static %}
{% load blog_tags %}
{% block contents %}
    <!-- breadcrumb start-->
    <section class="breadcrumb breadcrumb_bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb_iner">
                        <div class="breadcrumb_iner_item">
                            <h2>Blog page</h2>
                            <p> <a href="{% url 'website:index' %}">Home</a> <span>-</span>Blog</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumb start-->


    <!--================Blog Area =================-->
    <section class="blog_area section_padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mb-5 mb-lg-0">       
                    <div class="blog_left_sidebar">
                        {% for post in posts %}               
                        <article class="blog_item">
                            <div class="blog_item_img">
                                <img class="card-img rounded-0" src="{{post.image.url}}" alt="">
                                <a href="#" class="blog_item_date">
                                    <h3>{{post.published_date|date:"d"}}</h3>
                                    <p>{{post.published_date|date:"M"}}</p>
                                </a>
                            </div>
                            <div class="blog_details">
                                <a class="d-inline-block" href="{% url 'blog:single' pid=post.id %}">
                                    <h2>{{post.title}}</h2>
                                </a>
                                <p>{{post.content|truncatewords:8|safe}}</p>
                                
                                <ul class="blog-info-link">
                                    {% for cat in post.category.all %}
                                    <li><a href="{% url 'blog:category' cat_name=cat.name %}"><i class="far fa-comments"></i>{{cat.name}}</a> {% if not forloop.last %},{% endif %}</li>
                                    {% endfor %}
                                    <li><i class="far fa-comments"></i>{% comments_count post.id %} Comments</li>
                                    <li><i class="far fa-views"></i>{{post.counted_views}} Views</li>
                                </ul>
                            </div>
                        </article>
                        {% endfor %}
                        <nav class="blog-pagination justify-content-center d-flex">
                            <ul class="pagination">
                                {% if posts.has_previous %}
                                <li class="page-item">
                                    <a href="?page={{ posts.previous_page_number }}" class="page-link" aria-label="Previous">
                                        <i class="ti-angle-left"></i>
                                    </a>
                                </li>
                                {% endif %}
                                {% for i in posts.paginator.page_range %}
						        {% if posts.number == i %}
                                <li class="page-item active">
                                    <a href="?page={{i}}" class="page-link">{{i}}</a>
                                </li>
                                
                                {% else %}
                                <li class="page-item">
                                    <a href="?page={{i}}" class="page-link">{{i}}</a>
                                </li>
                                {% endif %}
                                {% endfor %}
                                {% if posts.has_next %}
                                <li class="page-item">
                                    <a href="?page={{ posts.next_page_number}}" class="page-link" aria-label="Next">
                                        <i class="ti-angle-right"></i>
                                    </a>
                                </li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="blog_right_sidebar">
                        {% include 'blog/blog-search.html' %}
                        {% postcategories %}
                        {% latestposts %}
                        {% include 'blog/blog-newsletter.html' %}
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--================Blog Area =================-->

    <!--::subscribe area start::-->
    <!-- <section class="subscribe_area">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-12">
                    <div class="subscribe_iner">
                        <div class="row align-items-center">
                            <div class="col-lg-5 col-xl-5">
                                <div class="subscribe_area_tittle">
                                    <h2>Do You Have a Question?</h2>
                                </div>
                            </div>
                            <div class="col-lg-7 col-xl-6">
                                <div id="mc_embed_signup">
                                    <aside class="single_sidebar_widget newsletter_widget">
                                        <form target="_blank"
                                            action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
                                            method="get">
                                            <div class="form-group">
                                                <input type="email" class="form-control" onfocus="this.placeholder = ''"
                                                    onblur="this.placeholder = 'Enter email'" placeholder='Enter email'
                                                    required>
                                            </div>
                                            <button class="btn_2" type="submit">Subscribe</button>

                                            <div class="info"></div>
                                        </form>
                                    </aside>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section> -->
    <!--::subscribe area end::-->
{% endblock %}

templates/blog/single-blog.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load blog_tags %}
{% block contents %}
   <!-- breadcrumb start-->
   <section class="breadcrumb breadcrumb_bg">
      <div class="container">
         <div class="row">
            <div class="col-lg-12">
               <div class="breadcrumb_iner">
                  <div class="breadcrumb_iner_item">
                     <h2>Blog single</h2>
                     <p> <a href="{% url 'website:index' %}">Home</a> <span>-</span>Blog single</p>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </section>
   <!-- breadcrumb start-->

   <!--================Blog Area =================-->
   <section class="blog_area single-post-area section_padding">
      <div class="container">
         <div class="row">
            <div class="col-lg-8 posts-list">
               <div class="single-post">
                  <div class="feature-img">
                     <img class="img-fluid" src="{{post.image.url}}" alt="">
                  </div>
                  <div class="blog_details">
                     <h2>{{post.title}}</h2>
                     <ul class="blog-info-link mt-3 mb-4">
                        {% for cat in post.category.all %}
                        <li><a href="#"><i class="far fa-comments"></i>{{cat.name}}</a> {% if not forloop.last %},{% endif %}</li>
                        {% endfor %}
                        <li><i class="far fa-comments"></i>{% comments_count post.id %} Comments</li>
                     </ul>
                     <p class="excert">{{post.content|safe}}</p>
                  </div>
               </div>
         
               <div class="navigation-top">
                  <div class="d-sm-flex justify-content-between text-center">
                     <p class="user-name col-lg-12 col-md-12 col-6">Written by: 
                        {% if post.author.first_name and post.author.last_name %}
                            {{ post.author.get_full_name }}  {# Shows "First Last" if both exist #}
                        {% else %}
                            {{ post.author.username }}  {# Falls back to username #}
                        {% endif %}</a>
                        <span class="lnr lnr-user"></span></p>
                     <div class="col-sm-4 text-center my-2 my-sm-0">
                        <p class="comment-count"><span class="align-middle"><i class="far fa-comment"></i></span> 06 Comments</p>
                     </div>
                     <ul class="social-icons">
                        <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                        <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fab fa-dribbble"></i></a></li>
                        <li><a href="#"><i class="fab fa-behance"></i></a></li>
                     </ul>
                  </div>
                  <div class="navigation-area">
                     <div class="row">
                        <div
                           class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
                           <div class="thumb">
                              {% if previous_post %}
                              <a href="{% url 'blog:single' pid=previous_post.id %}"><img class="ads-banner"
                                    src="{{previous_post.image.url}}" width="150" height="100" alt=""></a>
                           </div>
                           <div class="arrow">
                              <a href="{% url 'blog:single' pid=previous_post.id %}"><span
                                    class="lnr text-white lnr-arrow-left"></span></a>
                           </div>
                           <div class="detials">
                              <p>Prev Post</p>
                              <a href="{% url 'blog:single' pid=previous_post.id %}">
                                 <h4>{{ previous_post.title }}</h4>
                              </a>
                              {% endif %}
                           </div>
                        </div>
                        <div
                           class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
                           <div class="detials">
                              {% if next_post %}
                              <p>Next Post</p>
                              <a href="{% url 'blog:single' pid=next_post.id %}">
                                 <h4>{{next_post.title}}</h4>
                              </a>
                           </div>
                           <div class="arrow">
                              <a href="{% url 'blog:single' pid=next_post.id %}"><span
                                    class="lnr text-white lnr-arrow-right"></span></a>
                           </div>
                           <div class="thumb">
                              <a href="{% url 'blog:single' pid=next_post.id %}"><img class="img-fluid"
                                    src="{{next_post.image.url}}" width="150" height="100" alt=""></a>
                              {% endif %}
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="comments-area">
                  <h4>{{comments|length}} Comments</h4>
                  <div class="comment-list">
                  {% for comment in comments %}
                     <div class="single-comment justify-content-between d-flex">
                        <div class="user justify-content-between d-flex">
                           <div class="thumb">
                              <img src="{% static 'img/comment/comment_1.png' %}" alt="">
                           </div>
                           <div class="desc">
                              <div class="d-flex justify-content-between">
                                 <div class="d-flex align-items-center">
                                    <h5>
                                       <a href="#">{{comment.name}}</a>
                                    </h5>
                                 </div>
                                 <!-- <div class="reply-btn">
                                    <a href="#" class="btn-reply text-uppercase">reply</a>
                                 </div> -->
                              </div>
                              <p class="comment">
                                 {{comment.message}}
                              </p>
                           </div>
                        </div>
                        <p class="date">{{comment.created_date|naturalday}}</p>
                     </div>
                     {% empty %}
                     <p>no comment here, be the first one</p>
                  {% endfor %}
                  </div>
               </div>
               <div class="comment-form">
                  <h4>Leave a Comment</h4>
                  <form method="post" class="form-contact comment_form" action="{% url 'blog:single' pid=post.id %}">
                     {% csrf_token %}
                     <div class="row">
                        <input type="hidden" name="post" value="{{post.id}}">
                        {% if request.user.is_authenticated %}
                        <input type="hidden" name="name" value="{{request.user.get_full_name}}">
                        <!-- <input type="hidden" name="email" value="{{request.user.email}}"> -->
                        {% else %}
                        <div class="col-sm-6">
                           <div class="form-group">
                              <input class="form-control" name="name"  type="text" placeholder="Name">
                           </div> 
                        </div>
                        <div class="col-sm-6">
                           <div class="form-group">
                              <input class="form-control" name="email"  type="email" placeholder="Email">
                           </div>
                        </div>
                        {% endif %}
                        <div class="col-sm-6">
                           <div class="form-group">
                              <input class="form-control" name="subject"  type="text" placeholder="Subject">
                           </div>
                        </div>
                        <div class="col-12">
                           <div class="form-group">
                              <textarea class="form-control w-100" name="message" type="text"  cols="30" rows="9"
                                 placeholder="Write Comment"></textarea>
                           </div>
                        </div>
                     </div>
                     <div class="form-group">            
                        <button type="submit" class="button button-contactForm btn_1">Send Message</button>
                     </div>  
                  </form>
               </div>
            </div>
            <div class="col-lg-4">
               <div class="blog_right_sidebar">
                  {% include 'blog/blog-search.html' %}
                  {% postcategories %}
                  {% latestposts %}  
                  {% include 'blog/blog-tags.html' %}
                  {% include 'blog/blog-newsletter.html' %}
               </div>
            </div>
         </div>
      </div>
   </section>
   <!--================ Blog Area end =================-->

   <!--::subscribe area start::-->
   <!-- <section class="subscribe_area">
      <div class="container">
         <div class="row align-items-center">
            <div class="col-lg-12">
               <div class="subscribe_iner">
                  <div class="row align-items-center">
                     <div class="col-lg-5 col-xl-5">
                        <div class="subscribe_area_tittle">
                           <h2>Do You Have a Question?</h2>
                        </div>
                     </div>
                     <div class="col-lg-7 col-xl-6">
                        <div id="mc_embed_signup">
                           <aside class="single_sidebar_widget newsletter_widget">
                              <form target="_blank"
                                 action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
                                 method="get">
                                 <div class="form-group">
                                    <input type="email" class="form-control" onfocus="this.placeholder = ''"
                                       onblur="this.placeholder = 'Enter email'" placeholder='Enter email' required>
                                 </div>
                                 <button class="btn_2" type="submit">Subscribe</button>

                                 <div class="info"></div>
                              </form>
                           </aside>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </section> -->
   <!--::subscribe area end::-->
{% endblock %}